### ISSUE TITLE
/signals/file_process_status/ page throws error

### ISSUE THREAD

**Issue by ablwr** [bavc/signalserver#276] opened 2017-07-15 20:42 UTC
Going to this path on our test site gives this error: `list index out of range`

**Comment by yayoiukai** [comment] 2017-07-16 00:09
I look into it..

**Comment by yayoiukai** [comment] 2017-07-16 01:36
I can't reproduce it. So I will close it for now.

**Closed as completed by yayoiukai** 2017-07-16 01:36 UTC

**Comment by yayoiukai** [comment] 2017-07-16 01:57
Also, I think this is the same issue that Laura and Morgan posted earlier. So I treat this as a duplicate.
